# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 687)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setStyleSheet(".option_button {\n"
"    color: white;\n"
"    background-color: rgba(66, 66, 66, 1.0);\n"
"    border-radius :7px;\n"
"    font-size: 10.5pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
".option_button:hover {\n"
"    color: white;\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"\n"
".option_button:checked {\n"
"    color: rgb(66,66,66);\n"
"    background-color: rgb(89, 197, 255);\n"
"}\n"
"\n"
"#check_showOutliers {\n"
"    color: white;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setContentsMargins(-1, -1, -1, 0)
        self.mainLayout.setSpacing(5)
        self.mainLayout.setObjectName("mainLayout")
        self.vertical_list = QtWidgets.QVBoxLayout()
        self.vertical_list.setContentsMargins(-1, 0, -1, -1)
        self.vertical_list.setObjectName("vertical_list")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.label.setObjectName("label")
        self.vertical_list.addWidget(self.label)
        self.color_options = QtWidgets.QComboBox(parent=self.centralwidget)
        self.color_options.setMinimumSize(QtCore.QSize(0, 20))
        self.color_options.setStyleSheet("QComboBox {\n"
"    border-radius: 3px;\n"
"    padding: 3px;\n"
"    background-color: white;\n"
"    font: 17px;\n"
"    margin-bottom: 10px;\n"
"}")
        self.color_options.setObjectName("color_options")
        self.color_options.addItem("")
        self.color_options.addItem("")
        self.color_options.addItem("")
        self.color_options.addItem("")
        self.color_options.addItem("")
        self.color_options.addItem("")
        self.vertical_list.addWidget(self.color_options)
        self.listSplits = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listSplits.setMinimumSize(QtCore.QSize(120, 180))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        self.listSplits.setFont(font)
        self.listSplits.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.listSplits.setAutoFillBackground(False)
        self.listSplits.setStyleSheet("QListWidget {\n"
"    color: white;\n"
"    background-color: rgb(66, 66, 66);\n"
"    border-radius: 7px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget:item:hover {\n"
"    color: white;\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QListWidget:item:selected {\n"
"    color: rgb(66,66,66);\n"
"    background-color: rgb(89, 197, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.listSplits.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.listSplits.setSelectionRectVisible(False)
        self.listSplits.setObjectName("listSplits")
        item = QtWidgets.QListWidgetItem()
        self.listSplits.addItem(item)
        self.vertical_list.addWidget(self.listSplits)
        self.mainLayout.addLayout(self.vertical_list)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.options_gridLayout = QtWidgets.QGridLayout()
        self.options_gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.options_gridLayout.setContentsMargins(20, -1, 20, 0)
        self.options_gridLayout.setSpacing(3)
        self.options_gridLayout.setObjectName("options_gridLayout")
        self.option_personalBestOverAttempts = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_personalBestOverAttempts.sizePolicy().hasHeightForWidth())
        self.option_personalBestOverAttempts.setSizePolicy(sizePolicy)
        self.option_personalBestOverAttempts.setMinimumSize(QtCore.QSize(0, 40))
        self.option_personalBestOverAttempts.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option_personalBestOverAttempts.setFont(font)
        self.option_personalBestOverAttempts.setCheckable(True)
        self.option_personalBestOverAttempts.setChecked(False)
        self.option_personalBestOverAttempts.setAutoExclusive(True)
        self.option_personalBestOverAttempts.setObjectName("option_personalBestOverAttempts")
        self.option_buttons = QtWidgets.QButtonGroup(MainWindow)
        self.option_buttons.setObjectName("option_buttons")
        self.option_buttons.addButton(self.option_personalBestOverAttempts)
        self.options_gridLayout.addWidget(self.option_personalBestOverAttempts, 1, 3, 1, 1)
        self.option_hist = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_hist.sizePolicy().hasHeightForWidth())
        self.option_hist.setSizePolicy(sizePolicy)
        self.option_hist.setMinimumSize(QtCore.QSize(0, 40))
        self.option_hist.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option_hist.setFont(font)
        self.option_hist.setCheckable(True)
        self.option_hist.setChecked(False)
        self.option_hist.setAutoExclusive(True)
        self.option_hist.setAutoDefault(False)
        self.option_hist.setDefault(False)
        self.option_hist.setObjectName("option_hist")
        self.option_buttons.addButton(self.option_hist)
        self.options_gridLayout.addWidget(self.option_hist, 0, 0, 1, 1)
        self.option_impOverTime = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_impOverTime.sizePolicy().hasHeightForWidth())
        self.option_impOverTime.setSizePolicy(sizePolicy)
        self.option_impOverTime.setMinimumSize(QtCore.QSize(0, 40))
        self.option_impOverTime.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option_impOverTime.setFont(font)
        self.option_impOverTime.setCheckable(True)
        self.option_impOverTime.setChecked(False)
        self.option_impOverTime.setAutoExclusive(True)
        self.option_impOverTime.setObjectName("option_impOverTime")
        self.option_buttons.addButton(self.option_impOverTime)
        self.options_gridLayout.addWidget(self.option_impOverTime, 1, 2, 1, 1)
        self.option_movingAvg = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_movingAvg.sizePolicy().hasHeightForWidth())
        self.option_movingAvg.setSizePolicy(sizePolicy)
        self.option_movingAvg.setMinimumSize(QtCore.QSize(0, 40))
        self.option_movingAvg.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option_movingAvg.setFont(font)
        self.option_movingAvg.setCheckable(True)
        self.option_movingAvg.setChecked(False)
        self.option_movingAvg.setAutoExclusive(True)
        self.option_movingAvg.setObjectName("option_movingAvg")
        self.option_buttons.addButton(self.option_movingAvg)
        self.options_gridLayout.addWidget(self.option_movingAvg, 1, 0, 1, 1)
        self.option_impOverAttempts = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_impOverAttempts.sizePolicy().hasHeightForWidth())
        self.option_impOverAttempts.setSizePolicy(sizePolicy)
        self.option_impOverAttempts.setMinimumSize(QtCore.QSize(0, 40))
        self.option_impOverAttempts.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option_impOverAttempts.setFont(font)
        self.option_impOverAttempts.setCheckable(True)
        self.option_impOverAttempts.setChecked(False)
        self.option_impOverAttempts.setAutoExclusive(True)
        self.option_impOverAttempts.setObjectName("option_impOverAttempts")
        self.option_buttons.addButton(self.option_impOverAttempts)
        self.options_gridLayout.addWidget(self.option_impOverAttempts, 0, 2, 1, 1)
        self.option_personalBestOverTime = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_personalBestOverTime.sizePolicy().hasHeightForWidth())
        self.option_personalBestOverTime.setSizePolicy(sizePolicy)
        self.option_personalBestOverTime.setMinimumSize(QtCore.QSize(0, 40))
        self.option_personalBestOverTime.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.option_personalBestOverTime.setFont(font)
        self.option_personalBestOverTime.setCheckable(True)
        self.option_personalBestOverTime.setChecked(False)
        self.option_personalBestOverTime.setAutoExclusive(True)
        self.option_personalBestOverTime.setObjectName("option_personalBestOverTime")
        self.option_buttons.addButton(self.option_personalBestOverTime)
        self.options_gridLayout.addWidget(self.option_personalBestOverTime, 0, 3, 1, 1)
        self.check_showOutliers = QtWidgets.QCheckBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_showOutliers.sizePolicy().hasHeightForWidth())
        self.check_showOutliers.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_showOutliers.setFont(font)
        self.check_showOutliers.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.check_showOutliers.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.check_showOutliers.setStyleSheet("QCheckBox {\n"
"    margin-left: 10px;\n"
"}")
        self.check_showOutliers.setChecked(False)
        self.check_showOutliers.setObjectName("check_showOutliers")
        self.options_gridLayout.addWidget(self.check_showOutliers, 3, 0, 1, 1)
        self.option_attemptsOverTime = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.option_attemptsOverTime.sizePolicy().hasHeightForWidth())
        self.option_attemptsOverTime.setSizePolicy(sizePolicy)
        self.option_attemptsOverTime.setMinimumSize(QtCore.QSize(0, 40))
        self.option_attemptsOverTime.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.option_attemptsOverTime.setFont(font)
        self.option_attemptsOverTime.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.option_attemptsOverTime.setCheckable(True)
        self.option_attemptsOverTime.setChecked(False)
        self.option_attemptsOverTime.setAutoExclusive(True)
        self.option_attemptsOverTime.setObjectName("option_attemptsOverTime")
        self.option_buttons.addButton(self.option_attemptsOverTime)
        self.options_gridLayout.addWidget(self.option_attemptsOverTime, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.options_gridLayout)
        self.graph_layout = QtWidgets.QVBoxLayout()
        self.graph_layout.setContentsMargins(20, 20, 20, 20)
        self.graph_layout.setObjectName("graph_layout")
        self.graph_placeholder = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_placeholder.sizePolicy().hasHeightForWidth())
        self.graph_placeholder.setSizePolicy(sizePolicy)
        self.graph_placeholder.setStyleSheet("QWidget#placeholder {\n"
"    background: rgba(30,30,50,0);\n"
"}")
        self.graph_placeholder.setObjectName("graph_placeholder")
        self.graph_layout.addWidget(self.graph_placeholder)
        self.verticalLayout.addLayout(self.graph_layout)
        self.mainLayout.addLayout(self.verticalLayout)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 5)
        self.gridLayout.addLayout(self.mainLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.listSplits.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Graph Theme"))
        self.color_options.setItemText(0, _translate("MainWindow", "Superuser"))
        self.color_options.setItemText(1, _translate("MainWindow", "Alpine"))
        self.color_options.setItemText(2, _translate("MainWindow", "Shadow"))
        self.color_options.setItemText(3, _translate("MainWindow", "Dark Magic Girl"))
        self.color_options.setItemText(4, _translate("MainWindow", "Miami"))
        self.color_options.setItemText(5, _translate("MainWindow", "Sewing Tin Light"))
        __sortingEnabled = self.listSplits.isSortingEnabled()
        self.listSplits.setSortingEnabled(False)
        item = self.listSplits.item(0)
        item.setText(_translate("MainWindow", "xdd"))
        self.listSplits.setSortingEnabled(__sortingEnabled)
        self.option_personalBestOverAttempts.setText(_translate("MainWindow", "PB Over Attempts"))
        self.option_personalBestOverAttempts.setProperty("class", _translate("MainWindow", "option_button"))
        self.option_hist.setText(_translate("MainWindow", "Histogram"))
        self.option_hist.setProperty("class", _translate("MainWindow", "option_button"))
        self.option_impOverTime.setText(_translate("MainWindow", "Improvement Over Time"))
        self.option_impOverTime.setProperty("class", _translate("MainWindow", "option_button"))
        self.option_movingAvg.setText(_translate("MainWindow", "Moving Average"))
        self.option_movingAvg.setProperty("class", _translate("MainWindow", "option_button"))
        self.option_impOverAttempts.setText(_translate("MainWindow", "Improvement Over Attempts"))
        self.option_impOverAttempts.setProperty("class", _translate("MainWindow", "option_button"))
        self.option_personalBestOverTime.setText(_translate("MainWindow", "PB Over Time"))
        self.option_personalBestOverTime.setProperty("class", _translate("MainWindow", "option_button"))
        self.check_showOutliers.setText(_translate("MainWindow", "Show Outliers"))
        self.option_attemptsOverTime.setText(_translate("MainWindow", "Attempts Over Time"))
        self.option_attemptsOverTime.setProperty("class", _translate("MainWindow", "option_button"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
